// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGSvz3M9TPhCYAXM6CzvK3F-Unv95huE',
    appId: '1:936554363934:web:bf07b26aaebcec269f020f',
    messagingSenderId: '936554363934',
    projectId: 'myapp-17f8f',
    authDomain: 'myapp-17f8f.firebaseapp.com',
    storageBucket: 'myapp-17f8f.firebasestorage.app',
    measurementId: 'G-EKT1D2J9Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6wERFf3vfEy01IX5veXXxlTPYZNKaGRI',
    appId: '1:936554363934:android:412b3193f228ee8b9f020f',
    messagingSenderId: '936554363934',
    projectId: 'myapp-17f8f',
    databaseURL: 'https://myapp-17f8f-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-17f8f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqxi1K4FdsCNIY5Y-vYYfwit6HTsARh30',
    appId: '1:936554363934:ios:7e6c982adfdb466d9f020f',
    messagingSenderId: '936554363934',
    projectId: 'myapp-17f8f',
    storageBucket: 'myapp-17f8f.firebasestorage.app',
    iosBundleId: 'com.example.jApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqxi1K4FdsCNIY5Y-vYYfwit6HTsARh30',
    appId: '1:936554363934:ios:7e6c982adfdb466d9f020f',
    messagingSenderId: '936554363934',
    projectId: 'myapp-17f8f',
    storageBucket: 'myapp-17f8f.firebasestorage.app',
    iosBundleId: 'com.example.jApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkGSvz3M9TPhCYAXM6CzvK3F-Unv95huE',
    appId: '1:936554363934:web:331457c49e61ba319f020f',
    messagingSenderId: '936554363934',
    projectId: 'myapp-17f8f',
    authDomain: 'myapp-17f8f.firebaseapp.com',
    storageBucket: 'myapp-17f8f.firebasestorage.app',
    measurementId: 'G-SWZEW1M7PD',
  );
}
